#!/bin/bash
echo "****************************************************"
echo "**                                                **"
echo "** Intel provides sets of packages for several    **"
echo "** distributions on their web page in different   **"
echo "** states of brokenness.                          **"
echo "**                                                **"
echo "** Please follow their installation intructions   **"
echo "** and any online advice you can find until the   **"
echo "** configure script detects a valid ICD.          **"
echo "**                                                **"
echo "****************************************************"
