#!/bin/bash
echo "*************************************************"
echo "**                                             **"
echo "** This script will install all packages you   **"
echo "** need for the nVidia OpenCL driver to work   **"
echo "** on Ubuntu-based Linux distributions.        **"
echo "**                                             **"
echo "** The script needs 'sudo' rights to continue. **"
echo "**                                             **"
echo "*************************************************"
echo ""
sudo apt-get install nvidia-opencl-dev


echo ""
echo "*************************************************"
echo "** nVidia OpenCL development libs installed.   **"
echo "*************************************************"
echo ""
echo "WARNING: the ICD for the driver was not installed automatically on"
echo "         my test systems, you might have to install it manually."
echo ""
echo "         To do so, please check your driver version number:"
echo ""
echo "             > aptitude search '~i' | grep nvidia"
echo ""
echo "         there should be exactly one package listed of the form 'nvidia-###',"
echo "         the three digits are the driver version number."
echo ""
echo "         To install the corresponding ICD, use"
echo ""
echo "             > sudo apt-get install nvidia-opencl-icd-###"
echo ""
